name: build and release

on:
    release:
        types: [published]

jobs:
    tag:
        name: 🚛 Build and release
        runs-on: ubuntu-latest

        steps:
            - name: 🕶️ Checkout repository
              uses: actions/checkout@v3

            - name: 🤮 Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8
                  coverage: none
                  extensions: mbstring, intl
                  tools: composer:v2

            - name: 📦 Download dependencies
              run: |
                  composer install --no-dev --optimize-autoloader

            - name: 🗃️ Create artifact
              run: |
                  mkdir theme-build
                  composer archive -vvv --format=zip --file="theme-build/betheme-wordpress-headless-theme"

            - name: 🚛 Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: betheme-wordpress-headless-theme
                  path: theme-build/betheme-wordpress-headless-theme.zip

            - name: 🚀 Upload release asset
              uses: softprops/action-gh-release@v2
              with:
                  files: theme-build/betheme-wordpress-headless-theme.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
